export default [
  {
    files: ['src/**/*.js', 'scripts/**/*.mjs'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        crypto: 'readonly',
        fetch: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        WebSocketPair: 'readonly',
        ReadableStream: 'readonly',
        WritableStream: 'readonly',
        TransformStream: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        Blob: 'readonly',
        DataView: 'readonly',
        Uint8Array: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        console: 'readonly',
        Date: 'readonly',
        Number: 'readonly',
        String: 'readonly',
        Boolean: 'readonly',
        Object: 'readonly',
        Math: 'readonly',
        JSON: 'readonly',
        TypeError: 'readonly',
        Error: 'readonly',
        process: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { args: 'none' }],
      'no-undef': 'error',
    },
  },
];
